# Streamlit Secrets Configuration
# This file is for storing sensitive information like API keys, database credentials, etc.
# DO NOT commit this file to version control if it contains real secrets!

# Example configurations (replace with actual values when needed):

# [database]
# host = "your-database-host"
# port = 5432
# database = "your-database-name"
# username = "your-username"
# password = "your-password"

# [api_keys]
# openai_api_key = "your-openai-key"
# google_api_key = "your-google-key"

# [email]
# smtp_server = "smtp.gmail.com"
# smtp_port = 587
# email = "your-email@gmail.com"
# password = "your-app-password"

# Portfolio specific settings
[portfolio]
owner_name = "Arka Sain"
contact_email = "sainarka2@gmail.com"
phone_number = "+91 7410173864"
location = "Kolkata, West Bengal, India"

# Social media links (add your actual URLs)
[social_links]
linkedin = "https://www.linkedin.com/in/your-profile"
github = "https://github.com/your-username"
email = "mailto:sainarka2@gmail.com"

# Analytics (if you want to add Google Analytics later)
# [analytics]
# google_analytics_id = "G-XXXXXXXXXX"